name: Playwright Tests + Allure → GitHub Pages

on:
  push:
    branches:
      - ci_pipeline

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    env:
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI locally
        run: npm install -D allure-commandline

      - name: Install Playwright dependencies
        run: npx playwright install

      - name: Run Playwright tests
        run: npm run test:smoke

      - name: Generate Allure report into docs
        run: |
          rm -rf docs
          mkdir -p docs/history
          if [ -d docs/history ]; then
            cp -R docs/history/* docs/history/
          fi
          npx allure generate ./allure-results \
            --clean \
            --history docs/history \
            --output docs
          touch docs/.nojekyll

      - name: Commit and push Allure report
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "ci: update Allure report [skip ci]" || echo "No changes to commit"
          git push origin ci_pipeline