name: Playwright Tests + Allure → GitHub Pages

on:
  push:
    branches:
      - ci_pipeline    # or your primary branch

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    env:
      ADMIN_USERNAME: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_USERNAME }}  
    steps:
      # 1. Checkout the code (full history so we can later checkout gh-pages)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies & Allure CLI
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: npx playwright install

      - name: Install Allure CLI
        run: npm install -D allure-commandline

      # 4. Run your Playwright tests (writes raw results into allure-results/)
      - name: Run Playwright tests
        run: npm run test:smoke

      # 5. Fetch existing gh-pages branch (to grab previous history)
      - name: Fetch existing gh-pages
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
        continue-on-error: true    # branch may not exist on first run

      # 6. Generate an Allure report, preserving history
      - name: Generate Allure report
        run: |
          mkdir -p history
          if [ -d gh-pages/history ]; then
            cp -R gh-pages/history/* history/
          fi
          npx allure generate ./allure-results \
            --clean \
            --history history \
            --output allure-report

      # 7. Publish the `allure-report/` directory to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com