name: Regression Test Run

on:
  workflow_dispatch:

env:
  TEST_TYPE: regression

jobs:
  regression-tests:
    name: Regression Suite
    uses: ./.github/workflows/playwright-test-run.yml
    with:
      run_branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
      test_scope: regression
