name: Regression Test Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  regression-tests:
    name: Regression Suite
    uses: ./.github/workflows/playwright-test-run.yml
    with:
      run_branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
      test_scope: 'regression'
    secrets:
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}