name: Smoke Test Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke-tests:
    uses: ./.github/workflows/playwright-test-run.yml
    with:
      run_branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
      test_scope: 'smoke'
    secrets:
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}